var procedures = {
    "test": [
        "start the clock",
        "pull?",
        "intention check",
        "identify sut",
        "identify related tests",
        "control check",
        "branch?",
        "choose pyramid level",
        "modify vs add",
        "choose an audience",
        "focus on behaviour",
        "go to red",
        "investigate surprises",
        "improve red message",
        "time check",
        "revert?",
        "back to refactor?",
        "commit?"
    ],
    "code": [
        "start the clock",
        "go to green",
        "magic number is ok",
        "duplication is ok",
        "conditional is ok",
        "whatever is ok",
        "time check",
        "revert?",
        "commit?"
    ],
    "refactor": [
        "start the clock",
        "control check",
        "own the code",
        "own the tests",
        "magic number?",
        "duplication?",
        "bad name?",
        "primitive obsession?",
        "inappropriate intimacy?",
        "conditional?",
        "dead code?",
        "long method?",
        "god class?",
        "other code smells?",
        "s.o.l.i.d.?",
        "time check",
        "revert?",
        "commit?",
        "glad?",
        "afraid?"
    ]
};
